### ISSUE TITLE
Make Gem compatible with with Ruby 3.0, Ruby 3.1 and Ruby 3.2

### ISSUE THREAD

**Issue by diesl** [sms77io/ruby-client#1]
In the README.md file, it is stated that this Gem is compatible only with Ruby versions below (!) `3.0`. Ruby version `3.0` was released back in 2020.

This makes this Gem unusable for our company. Can you please make this Gem compatible with latest Ruby versions?

**Comment by matthiez** [comment]
Hi,
v0.5.0 passed the tests and just got published. Hope this helps!

**Comment by diesl** [comment]
Thanks @matthiez for quick reaction 👍 

You forgot to fix the README.md file though, I left a comment at the respective line in your commit
