### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by diesl** [sms77io/ruby-client#3]
Hi @matthiez 

originally I came here to request an update of the _faraday_ dependency, but then I realized that you already did some major rework, which also includes an upgrade of all dependecies 👍 

Therefore I wanted to ask if you can release a new version to rubygems? 

I suspect because of the major refactoring, this will be a breaking change resulting in version 1.0? If this is the case, could you also add a Changelog file please?

Thanks!

**Comment by matthiez** [comment]
Hi @diesl,
yes I will sort this out in the upcoming week.


Happy Easter!

**Comment by diesl** [comment]
Thank you!

I wish you Happy Easter as well

**Comment by diesl** [comment]
Hi @matthiez, is there any chance you can release a new version in the near future?

**Comment by matthiez** [comment]
Hi @diesl ,
v0.6 is finally pushed - sorry for the delay!!

**Comment by diesl** [comment]
No problem - thanks for the release!

One question that is still open from the issue description:
Do you have any kind of **Changelog**? Would be nice to have at least a bit of information about what changed between releases.
